version: "3.8"

services:
  date-annotator:
    image: nlpsandbox/date-annotator-stub:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    container_name: date-annotator-stub
    networks:
      - nlp-sandbox
    ports:
      - "8080:8080"

networks:
  nlp-sandbox:
