name: Update to latest NLP Sandbox version

on:
  schedule:
    - cron: '0 10 * * *'  # everyday at 10am

jobs:
  check-and-update:
    name: Check and update to the latest NLP Sandbox version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest NLP Sandbox schemas version
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: nlpsandbox
          repo: nlpsandbox-schemas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new version to $GITHUB_ENV
        run: |
          new_version=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}
          echo "NEW_VERSION=$(echo $new_version)" >> $GITHUB_ENV

      - name: Start updating this NLP Sandbox tool
        run: |
          current_version=$(cat .nlpsandbox-version)
          new_version=${{ env.NEW_VERSION }}
          echo "${new_version}" > .nlpsandbox-version

          # Remove server folder so that everything is recreated
          rm -rf server
          npm ci
          npm run generate:server:latest

          for f in docker-compose.yml README.md; do
            sed -i "s/${current_version}/${new_version}/g" "$f"
          done

      - name: Send pull request to update to new version
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update to NLP Sandbox schemas ${{ env.NEW_VERSION }}
          commit-message: Update to NLP Sandbox schemas ${{ env.NEW_VERSION }}
          delete-branch: true
